nginx:
    build: ../build/nginx/1.14.0/
    links:
        - phpfpm
    volumes_from:
        - phpfpm
    ports:
        - "80:80"

phpfpm:
    build: ../build/php-fpm/7.2.6/
    volumes:
        - "./../../../../..:/var/www"