nginx:
    image: nginx:1.11.4
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ".:/var/www"

phpfpm:
    image: php-fpm:7.0
    volumes:
        - ".:/var/www"
    command: php-fpm

node:
    image: node:9.2.1
    volumes:
        - ".:/var/www"
    tty: true