nginx:
    ports:
        - "80:80"

phpfpm:
    net: "bridge"
    ports:
        - "7777:3306" # MySQL
    environment:
        APP_ENV: dev
    extra_hosts:
        - "site1.ss.local:172.17.0.1"

db:
    image:  mysql:5.6.19
    privileged: true
    net: "container:phpfpm"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO root@"%" IDENTIFIED BY "root";'
        MYSQL_DATABASE: "project"

memcached:
    image: memcached:latest
    net: "container:phpfpm"