<?php

namespace tests\unit\models;

use models\DesignBlockModel;

/**
 * Tests for model DesignTextModel
 *
 * @package tests\unit\models
 */
class DesignBlockModelTest extends AbstractModelTest
{

	/**
	 * Model object
	 *
	 * @return DesignBlockModel
	 */
	protected function getModel()
	{
		return new DesignBlockModel;
	}

	/**
	 * Data provider for CRUD test
	 *
	 * @return array
	 */
	public function dataProviderForCRUD()
	{
		return [
			// Insert: empty fields. Update: empty fields.
			[
				[],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
				[],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
			],
			// Insert: empty values. Update: empty values.
			[
				[
					"t.margin_top"                 => "",
					"t.margin_right"               => "",
					"t.margin_bottom"              => "",
					"t.margin_left"                => "",
					"t.padding_top"                => "",
					"t.padding_right"              => "",
					"t.padding_bottom"             => "",
					"t.padding_left"               => "",
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => "",
					"t.border_top_width"           => "",
					"t.border_top_left_radius"     => "",
					"t.border_right_width"         => "",
					"t.border_top_right_radius"    => "",
					"t.border_bottom_width"        => "",
					"t.border_bottom_right_radius" => "",
					"t.border_left_width"          => "",
					"t.border_bottom_left_radius"  => "",
					"t.border_color"               => "",
					"t.border_style"               => "",
				],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
				[
					"t.margin_top"                 => "",
					"t.margin_right"               => "",
					"t.margin_bottom"              => "",
					"t.margin_left"                => "",
					"t.padding_top"                => "",
					"t.padding_right"              => "",
					"t.padding_bottom"             => "",
					"t.padding_left"               => "",
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => "",
					"t.border_top_width"           => "",
					"t.border_top_left_radius"     => "",
					"t.border_right_width"         => "",
					"t.border_top_right_radius"    => "",
					"t.border_bottom_width"        => "",
					"t.border_bottom_right_radius" => "",
					"t.border_left_width"          => "",
					"t.border_bottom_left_radius"  => "",
					"t.border_color"               => "",
					"t.border_style"               => "",
				],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
			],
			// Insert: correct values. Update: correct values.
			[
				[
					"t.margin_top"                 => 10,
					"t.margin_right"               => 20,
					"t.margin_bottom"              => 30,
					"t.margin_left"                => 40,
					"t.padding_top"                => 15,
					"t.padding_right"              => 25,
					"t.padding_bottom"             => 35,
					"t.padding_left"               => 45,
					"t.background_color_from"      => "rgba(255,255,255,0.5)",
					"t.background_color_to"        => "rgb(0,0,0)",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
					"t.border_top_width"           => 1,
					"t.border_top_left_radius"     => 5,
					"t.border_right_width"         => 2,
					"t.border_top_right_radius"    => 10,
					"t.border_bottom_width"        => 3,
					"t.border_bottom_right_radius" => 15,
					"t.border_left_width"          => 4,
					"t.border_bottom_left_radius"  => 20,
					"t.border_color"               => "rgba(0,255,255,0.5)",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_SOLID,
				],
				[],
				[
					"t.margin_top"                 => 10,
					"t.margin_right"               => 20,
					"t.margin_bottom"              => 30,
					"t.margin_left"                => 40,
					"t.padding_top"                => 15,
					"t.padding_right"              => 25,
					"t.padding_bottom"             => 35,
					"t.padding_left"               => 45,
					"t.background_color_from"      => "rgba(255,255,255,0.5)",
					"t.background_color_to"        => "rgb(0,0,0)",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
					"t.border_top_width"           => 1,
					"t.border_top_left_radius"     => 5,
					"t.border_right_width"         => 2,
					"t.border_top_right_radius"    => 10,
					"t.border_bottom_width"        => 3,
					"t.border_bottom_right_radius" => 15,
					"t.border_left_width"          => 4,
					"t.border_bottom_left_radius"  => 20,
					"t.border_color"               => "rgba(0,255,255,0.5)",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_SOLID,
				],
				[
					"t.margin_top"                 => "5",
					"t.margin_right"               => "6",
					"t.margin_bottom"              => "7",
					"t.margin_left"                => "8",
					"t.padding_top"                => "9",
					"t.padding_right"              => "10",
					"t.padding_bottom"             => "11",
					"t.padding_left"               => "12",
					"t.background_color_from"      => "rgba(255,0,255,0.5)",
					"t.background_color_to"        => "rgba(255,255,0,0.5)",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
					"t.border_top_width"           => "3",
					"t.border_top_left_radius"     => "4",
					"t.border_right_width"         => "5",
					"t.border_top_right_radius"    => "6",
					"t.border_bottom_width"        => "7",
					"t.border_bottom_right_radius" => "8",
					"t.border_left_width"          => "9",
					"t.border_bottom_left_radius"  => "10",
					"t.border_color"               => "rgb(0,255,0)",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_DOTTED,
				],
				[],
				[
					"t.margin_top"                 => 5,
					"t.margin_right"               => 6,
					"t.margin_bottom"              => 7,
					"t.margin_left"                => 8,
					"t.padding_top"                => 9,
					"t.padding_right"              => 10,
					"t.padding_bottom"             => 11,
					"t.padding_left"               => 12,
					"t.background_color_from"      => "rgba(255,0,255,0.5)",
					"t.background_color_to"        => "rgba(255,255,0,0.5)",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
					"t.border_top_width"           => 3,
					"t.border_top_left_radius"     => 4,
					"t.border_right_width"         => 5,
					"t.border_top_right_radius"    => 6,
					"t.border_bottom_width"        => 7,
					"t.border_bottom_right_radius" => 8,
					"t.border_left_width"          => 9,
					"t.border_bottom_left_radius"  => 10,
					"t.border_color"               => "rgb(0,255,0)",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_DOTTED,
				],
			],
			// Insert: values with incorrect type. Update: values with incorrect type
			[
				[
					"t.margin_top"                 => "incorrect type",
					"t.margin_right"               => "incorrect type",
					"t.margin_bottom"              => "incorrect type",
					"t.margin_left"                => "incorrect type",
					"t.padding_top"                => "incorrect type",
					"t.padding_right"              => "incorrect type",
					"t.padding_bottom"             => "incorrect type",
					"t.padding_left"               => "incorrect type",
					"t.background_color_from"      => "incorrect type",
					"t.background_color_to"        => "incorrect type",
					"t.gradient_direction"         => "incorrect type",
					"t.border_top_width"           => "incorrect type",
					"t.border_top_left_radius"     => "incorrect type",
					"t.border_right_width"         => "incorrect type",
					"t.border_top_right_radius"    => "incorrect type",
					"t.border_bottom_width"        => "incorrect type",
					"t.border_bottom_right_radius" => "incorrect type",
					"t.border_left_width"          => "incorrect type",
					"t.border_bottom_left_radius"  => "incorrect type",
					"t.border_color"               => "0,255,255,0.5",
					"t.border_style"               => "incorrect type",
				],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
				[
					"t.margin_top"                 => "incorrect type",
					"t.margin_right"               => "incorrect type",
					"t.margin_bottom"              => "incorrect type",
					"t.margin_left"                => "incorrect type",
					"t.padding_top"                => "incorrect type",
					"t.padding_right"              => "incorrect type",
					"t.padding_bottom"             => "incorrect type",
					"t.padding_left"               => "incorrect type",
					"t.background_color_from"      => "incorrect type",
					"t.background_color_to"        => "incorrect type",
					"t.gradient_direction"         => "incorrect type",
					"t.border_top_width"           => "incorrect type",
					"t.border_top_left_radius"     => "incorrect type",
					"t.border_right_width"         => "incorrect type",
					"t.border_top_right_radius"    => "incorrect type",
					"t.border_bottom_width"        => "incorrect type",
					"t.border_bottom_right_radius" => "incorrect type",
					"t.border_left_width"          => "incorrect type",
					"t.border_bottom_left_radius"  => "incorrect type",
					"t.border_color"               => "#cccccc",
					"t.border_style"               => "incorrect type",
				],
				[],
				[
					"t.margin_top"                 => 0,
					"t.margin_right"               => 0,
					"t.margin_bottom"              => 0,
					"t.margin_left"                => 0,
					"t.padding_top"                => 0,
					"t.padding_right"              => 0,
					"t.padding_bottom"             => 0,
					"t.padding_left"               => 0,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => 0,
					"t.border_top_width"           => 0,
					"t.border_top_left_radius"     => 0,
					"t.border_right_width"         => 0,
					"t.border_top_right_radius"    => 0,
					"t.border_bottom_width"        => 0,
					"t.border_bottom_right_radius" => 0,
					"t.border_left_width"          => 0,
					"t.border_bottom_left_radius"  => 0,
					"t.border_color"               => "",
					"t.border_style"               => 0,
				],
			],
			// Insert: values with incorrect values. Update: values with incorrect values
			[
				[
					"t.margin_top"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_right"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_bottom"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_left"                => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.padding_top"                => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_right"              => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_bottom"             => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_left"               => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.background_color_from"      => "#ccc",
					"t.background_color_to"        => "#cccccc",
					"t.gradient_direction"         => 99,
					"t.border_top_width"           => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_top_left_radius"     => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_right_width"         => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_top_right_radius"    => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_bottom_width"        => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_bottom_right_radius" => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_left_width"          => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_bottom_left_radius"  => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_color"               => "0,255,255",
					"t.border_style"               => 99,
				],
				[],
				[
					"t.margin_top"                 => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_right"               => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_bottom"              => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_left"                => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.padding_top"                => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_right"              => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_bottom"             => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_left"               => DesignBlockModel::MIN_PADDING_VALUE,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
					"t.border_top_width"           => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_top_left_radius"     => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_right_width"         => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_top_right_radius"    => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_bottom_width"        => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_bottom_right_radius" => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_left_width"          => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_bottom_left_radius"  => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_color"               => "",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_NONE,
				],
				[
					"t.margin_top"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_right"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_bottom"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.margin_left"                => DesignBlockModel::MIN_MARGIN_VALUE - 1,
					"t.padding_top"                => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_right"              => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_bottom"             => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.padding_left"               => DesignBlockModel::MIN_PADDING_VALUE - 1,
					"t.background_color_from"      => "0,255,255",
					"t.background_color_to"        => "0,0,255",
					"t.gradient_direction"         => 111,
					"t.border_top_width"           => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_top_left_radius"     => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_right_width"         => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_top_right_radius"    => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_bottom_width"        => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_bottom_right_radius" => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_left_width"          => DesignBlockModel::MIN_BORDER_WIDTH_VALUE - 1,
					"t.border_bottom_left_radius"  => DesignBlockModel::MIN_BORDER_RADIUS_VALUE - 1,
					"t.border_color"               => "#cccccc",
					"t.border_style"               => 111,
				],
				[],
				[
					"t.margin_top"                 => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_right"               => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_bottom"              => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.margin_left"                => DesignBlockModel::MIN_MARGIN_VALUE,
					"t.padding_top"                => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_right"              => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_bottom"             => DesignBlockModel::MIN_PADDING_VALUE,
					"t.padding_left"               => DesignBlockModel::MIN_PADDING_VALUE,
					"t.background_color_from"      => "",
					"t.background_color_to"        => "",
					"t.gradient_direction"         => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
					"t.border_top_width"           => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_top_left_radius"     => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_right_width"         => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_top_right_radius"    => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_bottom_width"        => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_bottom_right_radius" => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_left_width"          => DesignBlockModel::MIN_BORDER_WIDTH_VALUE,
					"t.border_bottom_left_radius"  => DesignBlockModel::MIN_BORDER_RADIUS_VALUE,
					"t.border_color"               => "",
					"t.border_style"               => DesignBlockModel::BORDER_STYLE_NONE,
				],
			],
		];
	}
}