<?php

namespace testS\tests\unit\models;

use testS\models\DesignBlockModel;

/**
 * Tests for the model DesignBlockModel
 *
 * @package testS\tests\unit\models
 */
class DesignBlockModelTest extends AbstractModelTest
{

    /**
     * Gets model name
     *
     * @return DesignBlockModel
     */
    protected function getNewModel()
    {
        return new DesignBlockModel();
    }

    /**
     * Data provider for CRUD. Empty values
     *
     * @return array
     */
    protected function getDataProviderCRUDEmpty()
    {
        return [
            "empty1" => [
                [],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
                [
                    "marginTop"                    => "",
                    "marginRight"                  => "",
                    "marginBottom"                 => "",
                    "marginLeft"                   => "",
                    "paddingTop"                   => "",
                    "paddingRight"                 => "",
                    "paddingBottom"                => "",
                    "paddingLeft"                  => "",
                    "backgroundColorFrom"          => "",
                    "backgroundColorTo"            => "",
                    "gradientDirection"            => "",
                    "borderTopWidth"               => "",
                    "borderTopLeftRadius"          => "",
                    "borderRightWidth"             => "",
                    "borderTopRightRadius"         => "",
                    "borderBottomWidth"            => "",
                    "borderBottomRightRadius"      => "",
                    "borderLeftWidth"              => "",
                    "borderBottomLeftRadius"       => "",
                    "borderColor"                  => "",
                    "borderStyle"                  => "",
                    "marginTopHover"               => "",
                    "marginRightHover"             => "",
                    "marginBottomHover"            => "",
                    "marginLeftHover"              => "",
                    "paddingTopHover"              => "",
                    "paddingRightHover"            => "",
                    "paddingBottomHover"           => "",
                    "paddingLeftHover"             => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirectionHover"       => "",
                    "borderTopWidthHover"          => "",
                    "borderTopLeftRadiusHover"     => "",
                    "borderRightWidthHover"        => "",
                    "borderTopRightRadiusHover"    => "",
                    "borderBottomWidthHover"       => "",
                    "borderBottomRightRadiusHover" => "",
                    "borderLeftWidthHover"         => "",
                    "borderBottomLeftRadiusHover"  => "",
                    "borderColorHover"             => "",
                    "borderStyleHover"             => "",
                    "hasMarginAnimation"           => "",
                    "hasPaddingAnimation"          => "",
                    "hasBackgroundAnimation"       => "",
                    "hasBorderRadiusAnimation"     => "",
                    "hasBorderAnimation"           => "",
                    "width"                        => "",
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
            ],
            "empty2" => [
                [
                    "marginTop"                    => null,
                    "marginRight"                  => null,
                    "marginBottom"                 => null,
                    "marginLeft"                   => null,
                    "paddingTop"                   => null,
                    "paddingRight"                 => null,
                    "paddingBottom"                => null,
                    "paddingLeft"                  => null,
                    "backgroundColorFrom"          => null,
                    "backgroundColorTo"            => null,
                    "gradientDirection"            => null,
                    "borderTopWidth"               => null,
                    "borderTopLeftRadius"          => null,
                    "borderRightWidth"             => null,
                    "borderTopRightRadius"         => null,
                    "borderBottomWidth"            => null,
                    "borderBottomRightRadius"      => null,
                    "borderLeftWidth"              => null,
                    "borderBottomLeftRadius"       => null,
                    "borderColor"                  => null,
                    "borderStyle"                  => null,
                    "marginTopHover"               => null,
                    "marginRightHover"             => null,
                    "marginBottomHover"            => null,
                    "marginLeftHover"              => null,
                    "paddingTopHover"              => null,
                    "paddingRightHover"            => null,
                    "paddingBottomHover"           => null,
                    "paddingLeftHover"             => null,
                    "backgroundColorFromHover"     => null,
                    "backgroundColorToHover"       => null,
                    "gradientDirectionHover"       => null,
                    "borderTopWidthHover"          => null,
                    "borderTopLeftRadiusHover"     => null,
                    "borderRightWidthHover"        => null,
                    "borderTopRightRadiusHover"    => null,
                    "borderBottomWidthHover"       => null,
                    "borderBottomRightRadiusHover" => null,
                    "borderLeftWidthHover"         => null,
                    "borderBottomLeftRadiusHover"  => null,
                    "borderColorHover"             => null,
                    "borderStyleHover"             => null,
                    "hasMarginAnimation"           => null,
                    "hasPaddingAnimation"          => null,
                    "hasBackgroundAnimation"       => null,
                    "hasBorderRadiusAnimation"     => null,
                    "hasBorderAnimation"           => null,
                    "width"                        => null,
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
                [
                    "marginTop"                    => "  ",
                    "marginRight"                  => "  ",
                    "marginBottom"                 => "  ",
                    "marginLeft"                   => "  ",
                    "paddingTop"                   => "  ",
                    "paddingRight"                 => "  ",
                    "paddingBottom"                => "  ",
                    "paddingLeft"                  => "  ",
                    "backgroundColorFrom"          => "  ",
                    "backgroundColorTo"            => "  ",
                    "gradientDirection"            => "  ",
                    "borderTopWidth"               => "  ",
                    "borderTopLeftRadius"          => "  ",
                    "borderRightWidth"             => "  ",
                    "borderTopRightRadius"         => "  ",
                    "borderBottomWidth"            => "  ",
                    "borderBottomRightRadius"      => "  ",
                    "borderLeftWidth"              => "  ",
                    "borderBottomLeftRadius"       => "  ",
                    "borderColor"                  => "  ",
                    "borderStyle"                  => "  ",
                    "marginTopHover"               => "  ",
                    "marginRightHover"             => "  ",
                    "marginBottomHover"            => "  ",
                    "marginLeftHover"              => "  ",
                    "paddingTopHover"              => "  ",
                    "paddingRightHover"            => "  ",
                    "paddingBottomHover"           => "  ",
                    "paddingLeftHover"             => "  ",
                    "backgroundColorFromHover"     => "  ",
                    "backgroundColorToHover"       => "  ",
                    "gradientDirectionHover"       => "  ",
                    "borderTopWidthHover"          => "  ",
                    "borderTopLeftRadiusHover"     => "  ",
                    "borderRightWidthHover"        => "  ",
                    "borderTopRightRadiusHover"    => "  ",
                    "borderBottomWidthHover"       => "  ",
                    "borderBottomRightRadiusHover" => "  ",
                    "borderLeftWidthHover"         => "  ",
                    "borderBottomLeftRadiusHover"  => "  ",
                    "borderColorHover"             => "  ",
                    "borderStyleHover"             => "  ",
                    "hasMarginAnimation"           => "  ",
                    "hasPaddingAnimation"          => "  ",
                    "hasBackgroundAnimation"       => "  ",
                    "hasBorderRadiusAnimation"     => "  ",
                    "hasBorderAnimation"           => "  ",
                    "width"                        => "  ",
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
            ]
        ];
    }

    /**
     * Data provider for CRUD. Correct values
     *
     * @return array
     */
    protected function getDataProviderCRUDCorrect()
    {
        return [
            "correct1" => [
                [
                    "marginTop"                    => 10,
                    "marginRight"                  => 20,
                    "marginBottom"                 => 30,
                    "marginLeft"                   => 40,
                    "paddingTop"                   => 15,
                    "paddingRight"                 => 25,
                    "paddingBottom"                => 35,
                    "paddingLeft"                  => 45,
                    "backgroundColorFrom"          => "rgba(255,255,255,0.5)",
                    "backgroundColorTo"            => "rgb(0,0,0)",
                    "gradientDirection"            => 0,
                    "borderTopWidth"               => 1,
                    "borderTopLeftRadius"          => 5,
                    "borderRightWidth"             => 2,
                    "borderTopRightRadius"         => 10,
                    "borderBottomWidth"            => 3,
                    "borderBottomRightRadius"      => 15,
                    "borderLeftWidth"              => 4,
                    "borderBottomLeftRadius"       => 20,
                    "borderColor"                  => "rgba(0,255,255,0.5)",
                    "borderStyle"                  => 1,
                    "marginTopHover"               => 10,
                    "marginRightHover"             => 20,
                    "marginBottomHover"            => 30,
                    "marginLeftHover"              => 40,
                    "paddingTopHover"              => 15,
                    "paddingRightHover"            => 25,
                    "paddingBottomHover"           => 35,
                    "paddingLeftHover"             => 45,
                    "backgroundColorFromHover"     => "rgba(255,255,255,0.5)",
                    "backgroundColorToHover"       => "rgb(0,0,0)",
                    "gradientDirectionHover"       => 0,
                    "borderTopWidthHover"          => 1,
                    "borderTopLeftRadiusHover"     => 5,
                    "borderRightWidthHover"        => 2,
                    "borderTopRightRadiusHover"    => 10,
                    "borderBottomWidthHover"       => 3,
                    "borderBottomRightRadiusHover" => 15,
                    "borderLeftWidthHover"         => 4,
                    "borderBottomLeftRadiusHover"  => 20,
                    "borderColorHover"             => "rgba(0,255,255,0.5)",
                    "borderStyleHover"             => 1,
                    "hasMarginAnimation"           => true,
                    "hasPaddingAnimation"          => true,
                    "hasBackgroundAnimation"       => true,
                    "hasBorderRadiusAnimation"     => true,
                    "hasBorderAnimation"           => true,
                    "width"                        => 1024,
                ],
                [
                    "marginTop"                    => 10,
                    "marginRight"                  => 20,
                    "marginBottom"                 => 30,
                    "marginLeft"                   => 40,
                    "paddingTop"                   => 15,
                    "paddingRight"                 => 25,
                    "paddingBottom"                => 35,
                    "paddingLeft"                  => 45,
                    "backgroundColorFrom"          => "rgba(255,255,255,0.5)",
                    "backgroundColorTo"            => "rgb(0,0,0)",
                    "gradientDirection"            => 0,
                    "borderTopWidth"               => 1,
                    "borderTopLeftRadius"          => 5,
                    "borderRightWidth"             => 2,
                    "borderTopRightRadius"         => 10,
                    "borderBottomWidth"            => 3,
                    "borderBottomRightRadius"      => 15,
                    "borderLeftWidth"              => 4,
                    "borderBottomLeftRadius"       => 20,
                    "borderColor"                  => "rgba(0,255,255,0.5)",
                    "borderStyle"                  => 1,
                    "marginTopHover"               => 10,
                    "marginRightHover"             => 20,
                    "marginBottomHover"            => 30,
                    "marginLeftHover"              => 40,
                    "paddingTopHover"              => 15,
                    "paddingRightHover"            => 25,
                    "paddingBottomHover"           => 35,
                    "paddingLeftHover"             => 45,
                    "backgroundColorFromHover"     => "rgba(255,255,255,0.5)",
                    "backgroundColorToHover"       => "rgb(0,0,0)",
                    "gradientDirectionHover"       => 0,
                    "borderTopWidthHover"          => 1,
                    "borderTopLeftRadiusHover"     => 5,
                    "borderRightWidthHover"        => 2,
                    "borderTopRightRadiusHover"    => 10,
                    "borderBottomWidthHover"       => 3,
                    "borderBottomRightRadiusHover" => 15,
                    "borderLeftWidthHover"         => 4,
                    "borderBottomLeftRadiusHover"  => 20,
                    "borderColorHover"             => "rgba(0,255,255,0.5)",
                    "borderStyleHover"             => 1,
                    "hasMarginAnimation"           => true,
                    "hasPaddingAnimation"          => true,
                    "hasBackgroundAnimation"       => true,
                    "hasBorderRadiusAnimation"     => true,
                    "hasBorderAnimation"           => true,
                    "width"                        => 1024,
                ],
                [
                    "marginTop"                    => 5,
                    "marginRight"                  => 6,
                    "marginBottom"                 => 7,
                    "marginLeft"                   => 8,
                    "paddingTop"                   => 9,
                    "paddingRight"                 => 10,
                    "paddingBottom"                => 11,
                    "paddingLeft"                  => 12,
                    "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
                    "backgroundColorTo"            => "rgba(255,255,0,0.5)",
                    "gradientDirection"            => 1,
                    "borderTopWidth"               => 3,
                    "borderTopLeftRadius"          => 4,
                    "borderRightWidth"             => 5,
                    "borderTopRightRadius"         => 6,
                    "borderBottomWidth"            => 7,
                    "borderBottomRightRadius"      => 8,
                    "borderLeftWidth"              => 9,
                    "borderBottomLeftRadius"       => 10,
                    "borderColor"                  => "rgb(0,255,0)",
                    "borderStyle"                  => 2,
                    "marginTopHover"               => 5,
                    "marginRightHover"             => 6,
                    "marginBottomHover"            => 7,
                    "marginLeftHover"              => 8,
                    "paddingTopHover"              => 9,
                    "paddingRightHover"            => 10,
                    "paddingBottomHover"           => 11,
                    "paddingLeftHover"             => 12,
                    "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
                    "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
                    "gradientDirectionHover"       => 1,
                    "borderTopWidthHover"          => 3,
                    "borderTopLeftRadiusHover"     => 4,
                    "borderRightWidthHover"        => 5,
                    "borderTopRightRadiusHover"    => 6,
                    "borderBottomWidthHover"       => 7,
                    "borderBottomRightRadiusHover" => 8,
                    "borderLeftWidthHover"         => 9,
                    "borderBottomLeftRadiusHover"  => 10,
                    "borderColorHover"             => "rgb(0,255,0)",
                    "borderStyleHover"             => 2,
                    "hasMarginAnimation"           => false,
                    "hasPaddingAnimation"          => false,
                    "hasBackgroundAnimation"       => false,
                    "hasBorderRadiusAnimation"     => false,
                    "hasBorderAnimation"           => false,
                    "width"                        => 980,
                ],
                [
                    "marginTop"                    => 5,
                    "marginRight"                  => 6,
                    "marginBottom"                 => 7,
                    "marginLeft"                   => 8,
                    "paddingTop"                   => 9,
                    "paddingRight"                 => 10,
                    "paddingBottom"                => 11,
                    "paddingLeft"                  => 12,
                    "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
                    "backgroundColorTo"            => "rgba(255,255,0,0.5)",
                    "gradientDirection"            => 1,
                    "borderTopWidth"               => 3,
                    "borderTopLeftRadius"          => 4,
                    "borderRightWidth"             => 5,
                    "borderTopRightRadius"         => 6,
                    "borderBottomWidth"            => 7,
                    "borderBottomRightRadius"      => 8,
                    "borderLeftWidth"              => 9,
                    "borderBottomLeftRadius"       => 10,
                    "borderColor"                  => "rgb(0,255,0)",
                    "borderStyle"                  => 2,
                    "marginTopHover"               => 5,
                    "marginRightHover"             => 6,
                    "marginBottomHover"            => 7,
                    "marginLeftHover"              => 8,
                    "paddingTopHover"              => 9,
                    "paddingRightHover"            => 10,
                    "paddingBottomHover"           => 11,
                    "paddingLeftHover"             => 12,
                    "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
                    "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
                    "gradientDirectionHover"       => 1,
                    "borderTopWidthHover"          => 3,
                    "borderTopLeftRadiusHover"     => 4,
                    "borderRightWidthHover"        => 5,
                    "borderTopRightRadiusHover"    => 6,
                    "borderBottomWidthHover"       => 7,
                    "borderBottomRightRadiusHover" => 8,
                    "borderLeftWidthHover"         => 9,
                    "borderBottomLeftRadiusHover"  => 10,
                    "borderColorHover"             => "rgb(0,255,0)",
                    "borderStyleHover"             => 2,
                    "hasMarginAnimation"           => false,
                    "hasPaddingAnimation"          => false,
                    "hasBackgroundAnimation"       => false,
                    "hasBorderRadiusAnimation"     => false,
                    "hasBorderAnimation"           => false,
                    "width"                        => 980,
                ]
            ],
            "correct2" => [
                [
                    "marginTop"                    => 5,
                    "marginRight"                  => 6,
                    "marginBottom"                 => 7,
                    "marginLeft"                   => 8,
                    "paddingTop"                   => 9,
                    "paddingRight"                 => 10,
                    "paddingBottom"                => 11,
                    "paddingLeft"                  => 12,
                    "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
                    "backgroundColorTo"            => "rgba(255,255,0,0.5)",
                    "gradientDirection"            => 1,
                    "borderTopWidth"               => 3,
                    "borderTopLeftRadius"          => 4,
                    "borderRightWidth"             => 5,
                    "borderTopRightRadius"         => 6,
                    "borderBottomWidth"            => 7,
                    "borderBottomRightRadius"      => 8,
                    "borderLeftWidth"              => 9,
                    "borderBottomLeftRadius"       => 10,
                    "borderColor"                  => "rgb(0,255,0)",
                    "borderStyle"                  => 2,
                    "marginTopHover"               => 5,
                    "marginRightHover"             => 6,
                    "marginBottomHover"            => 7,
                    "marginLeftHover"              => 8,
                    "paddingTopHover"              => 9,
                    "paddingRightHover"            => 10,
                    "paddingBottomHover"           => 11,
                    "paddingLeftHover"             => 12,
                    "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
                    "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
                    "gradientDirectionHover"       => 1,
                    "borderTopWidthHover"          => 3,
                    "borderTopLeftRadiusHover"     => 4,
                    "borderRightWidthHover"        => 5,
                    "borderTopRightRadiusHover"    => 6,
                    "borderBottomWidthHover"       => 7,
                    "borderBottomRightRadiusHover" => 8,
                    "borderLeftWidthHover"         => 9,
                    "borderBottomLeftRadiusHover"  => 10,
                    "borderColorHover"             => "rgb(0,255,0)",
                    "borderStyleHover"             => 2,
                    "hasMarginAnimation"           => false,
                    "hasPaddingAnimation"          => false,
                    "hasBackgroundAnimation"       => false,
                    "hasBorderRadiusAnimation"     => false,
                    "hasBorderAnimation"           => false,
                    "width"                        => 980,
                ],
                [
                    "marginTop"                    => 5,
                    "marginRight"                  => 6,
                    "marginBottom"                 => 7,
                    "marginLeft"                   => 8,
                    "paddingTop"                   => 9,
                    "paddingRight"                 => 10,
                    "paddingBottom"                => 11,
                    "paddingLeft"                  => 12,
                    "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
                    "backgroundColorTo"            => "rgba(255,255,0,0.5)",
                    "gradientDirection"            => 1,
                    "borderTopWidth"               => 3,
                    "borderTopLeftRadius"          => 4,
                    "borderRightWidth"             => 5,
                    "borderTopRightRadius"         => 6,
                    "borderBottomWidth"            => 7,
                    "borderBottomRightRadius"      => 8,
                    "borderLeftWidth"              => 9,
                    "borderBottomLeftRadius"       => 10,
                    "borderColor"                  => "rgb(0,255,0)",
                    "borderStyle"                  => 2,
                    "marginTopHover"               => 5,
                    "marginRightHover"             => 6,
                    "marginBottomHover"            => 7,
                    "marginLeftHover"              => 8,
                    "paddingTopHover"              => 9,
                    "paddingRightHover"            => 10,
                    "paddingBottomHover"           => 11,
                    "paddingLeftHover"             => 12,
                    "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
                    "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
                    "gradientDirectionHover"       => 1,
                    "borderTopWidthHover"          => 3,
                    "borderTopLeftRadiusHover"     => 4,
                    "borderRightWidthHover"        => 5,
                    "borderTopRightRadiusHover"    => 6,
                    "borderBottomWidthHover"       => 7,
                    "borderBottomRightRadiusHover" => 8,
                    "borderLeftWidthHover"         => 9,
                    "borderBottomLeftRadiusHover"  => 10,
                    "borderColorHover"             => "rgb(0,255,0)",
                    "borderStyleHover"             => 2,
                    "hasMarginAnimation"           => false,
                    "hasPaddingAnimation"          => false,
                    "hasBackgroundAnimation"       => false,
                    "hasBorderRadiusAnimation"     => false,
                    "hasBorderAnimation"           => false,
                    "width"                        => 980,
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ]
            ]
        ];
    }

    /**
     * Data provider for CRUD. Incorrect values
     *
     * @return array
     */
    protected function getDataProviderCRUDIncorrect()
    {
        return [
            "incorrect1" => [
                [
                    "marginTop"                    => "  10   ",
                    "marginRight"                  => "20",
                    "marginBottom"                 => "30",
                    "marginLeft"                   => "40",
                    "paddingTop"                   => "  15  ",
                    "paddingRight"                 => "25",
                    "paddingBottom"                => "35",
                    "paddingLeft"                  => "45",
                    "backgroundColorFrom"          => "   rgba(255,255,255,0.5)   ",
                    "backgroundColorTo"            => "   rgb(0,0,0)   ",
                    "gradientDirection"            => "0",
                    "borderTopWidth"               => "1",
                    "borderTopLeftRadius"          => "5",
                    "borderRightWidth"             => "2",
                    "borderTopRightRadius"         => "  10  ",
                    "borderBottomWidth"            => " 3  ",
                    "borderBottomRightRadius"      => "15",
                    "borderLeftWidth"              => "4",
                    "borderBottomLeftRadius"       => "20",
                    "borderColor"                  => "  rgba(0,255,255,0.5)  ",
                    "borderStyle"                  => "1",
                    "marginTopHover"               => "10",
                    "marginRightHover"             => "20",
                    "marginBottomHover"            => "  30  ",
                    "marginLeftHover"              => "40",
                    "paddingTopHover"              => "15",
                    "paddingRightHover"            => "25",
                    "paddingBottomHover"           => "35",
                    "paddingLeftHover"             => "45",
                    "backgroundColorFromHover"     => "  rgba(255,255,255,0.5)  ",
                    "backgroundColorToHover"       => "  rgb(0,0,0)  ",
                    "gradientDirectionHover"       => "0",
                    "borderTopWidthHover"          => "1",
                    "borderTopLeftRadiusHover"     => "5",
                    "borderRightWidthHover"        => "2",
                    "borderTopRightRadiusHover"    => "10",
                    "borderBottomWidthHover"       => "3",
                    "borderBottomRightRadiusHover" => "15",
                    "borderLeftWidthHover"         => "4",
                    "borderBottomLeftRadiusHover"  => "20",
                    "borderColorHover"             => " rgba(0,255,255,0.5) ",
                    "borderStyleHover"             => "1",
                    "hasMarginAnimation"           => "1",
                    "hasPaddingAnimation"          => " true ",
                    "hasBackgroundAnimation"       => "true",
                    "hasBorderRadiusAnimation"     => "1",
                    "hasBorderAnimation"           => "1",
                    "width"                        => "1024",
                ],
                [
                    "marginTop"                    => 10,
                    "marginRight"                  => 20,
                    "marginBottom"                 => 30,
                    "marginLeft"                   => 40,
                    "paddingTop"                   => 15,
                    "paddingRight"                 => 25,
                    "paddingBottom"                => 35,
                    "paddingLeft"                  => 45,
                    "backgroundColorFrom"          => "rgba(255,255,255,0.5)",
                    "backgroundColorTo"            => "rgb(0,0,0)",
                    "gradientDirection"            => 0,
                    "borderTopWidth"               => 1,
                    "borderTopLeftRadius"          => 5,
                    "borderRightWidth"             => 2,
                    "borderTopRightRadius"         => 10,
                    "borderBottomWidth"            => 3,
                    "borderBottomRightRadius"      => 15,
                    "borderLeftWidth"              => 4,
                    "borderBottomLeftRadius"       => 20,
                    "borderColor"                  => "rgba(0,255,255,0.5)",
                    "borderStyle"                  => 1,
                    "marginTopHover"               => 10,
                    "marginRightHover"             => 20,
                    "marginBottomHover"            => 30,
                    "marginLeftHover"              => 40,
                    "paddingTopHover"              => 15,
                    "paddingRightHover"            => 25,
                    "paddingBottomHover"           => 35,
                    "paddingLeftHover"             => 45,
                    "backgroundColorFromHover"     => "rgba(255,255,255,0.5)",
                    "backgroundColorToHover"       => "rgb(0,0,0)",
                    "gradientDirectionHover"       => 0,
                    "borderTopWidthHover"          => 1,
                    "borderTopLeftRadiusHover"     => 5,
                    "borderRightWidthHover"        => 2,
                    "borderTopRightRadiusHover"    => 10,
                    "borderBottomWidthHover"       => 3,
                    "borderBottomRightRadiusHover" => 15,
                    "borderLeftWidthHover"         => 4,
                    "borderBottomLeftRadiusHover"  => 20,
                    "borderColorHover"             => "rgba(0,255,255,0.5)",
                    "borderStyleHover"             => 1,
                    "hasMarginAnimation"           => true,
                    "hasPaddingAnimation"          => true,
                    "hasBackgroundAnimation"       => true,
                    "hasBorderRadiusAnimation"     => true,
                    "hasBorderAnimation"           => true,
                    "width"                        => 1024,
                ],
                [
                    "marginTop"                    => "incorrect type",
                    "marginRight"                  => "incorrect type",
                    "marginBottom"                 => "incorrect type",
                    "marginLeft"                   => "incorrect type",
                    "paddingTop"                   => "incorrect type",
                    "paddingRight"                 => "incorrect type",
                    "paddingBottom"                => "incorrect type",
                    "paddingLeft"                  => "incorrect type",
                    "backgroundColorFrom"          => "incorrect type",
                    "backgroundColorTo"            => "incorrect type",
                    "gradientDirection"            => "incorrect type",
                    "borderTopWidth"               => "incorrect type",
                    "borderTopLeftRadius"          => "incorrect type",
                    "borderRightWidth"             => "incorrect type",
                    "borderTopRightRadius"         => "incorrect type",
                    "borderBottomWidth"            => "incorrect type",
                    "borderBottomRightRadius"      => "incorrect type",
                    "borderLeftWidth"              => "incorrect type",
                    "borderBottomLeftRadius"       => "incorrect type",
                    "borderColor"                  => "#cccccc",
                    "borderStyle"                  => "incorrect type",
                    "marginTopHover"               => "incorrect type",
                    "marginRightHover"             => "incorrect type",
                    "marginBottomHover"            => "incorrect type",
                    "marginLeftHover"              => "incorrect type",
                    "paddingTopHover"              => "incorrect type",
                    "paddingRightHover"            => "incorrect type",
                    "paddingBottomHover"           => "incorrect type",
                    "paddingLeftHover"             => "incorrect type",
                    "backgroundColorFromHover"     => "incorrect type",
                    "backgroundColorToHover"       => "incorrect type",
                    "gradientDirectionHover"       => "incorrect type",
                    "borderTopWidthHover"          => "incorrect type",
                    "borderTopLeftRadiusHover"     => "incorrect type",
                    "borderRightWidthHover"        => "incorrect type",
                    "borderTopRightRadiusHover"    => "incorrect type",
                    "borderBottomWidthHover"       => "incorrect type",
                    "borderBottomRightRadiusHover" => "incorrect type",
                    "borderLeftWidthHover"         => "incorrect type",
                    "borderBottomLeftRadiusHover"  => "incorrect type",
                    "borderColorHover"             => "0,255,255,0.5",
                    "borderStyleHover"             => "incorrect type",
                    "hasMarginAnimation"           => "incorrect type",
                    "hasPaddingAnimation"          => "incorrect type",
                    "hasBackgroundAnimation"       => "incorrect type",
                    "hasBorderRadiusAnimation"     => "incorrect type",
                    "hasBorderAnimation"           => "incorrect type",
                    "width"                        => "incorrect type",
                ],
                [
                    "marginTop"                    => 0,
                    "marginTopHover"               => 0,
                    "marginRight"                  => 0,
                    "marginRightHover"             => 0,
                    "marginBottom"                 => 0,
                    "marginBottomHover"            => 0,
                    "marginLeft"                   => 0,
                    "marginLeftHover"              => 0,
                    "hasMarginAnimation"           => false,
                    "paddingTop"                   => 0,
                    "paddingTopHover"              => 0,
                    "paddingRight"                 => 0,
                    "paddingRightHover"            => 0,
                    "paddingBottom"                => 0,
                    "paddingBottomHover"           => 0,
                    "paddingLeft"                  => 0,
                    "paddingLeftHover"             => 0,
                    "hasPaddingAnimation"          => false,
                    "backgroundColorFrom"          => "",
                    "backgroundColorFromHover"     => "",
                    "backgroundColorTo"            => "",
                    "backgroundColorToHover"       => "",
                    "gradientDirection"            => 0,
                    "gradientDirectionHover"       => 0,
                    "hasBackgroundAnimation"       => false,
                    "borderTopWidth"               => 0,
                    "borderTopWidthHover"          => 0,
                    "borderTopLeftRadius"          => 0,
                    "borderTopLeftRadiusHover"     => 0,
                    "borderRightWidth"             => 0,
                    "borderRightWidthHover"        => 0,
                    "borderTopRightRadius"         => 0,
                    "borderTopRightRadiusHover"    => 0,
                    "borderBottomWidth"            => 0,
                    "borderBottomWidthHover"       => 0,
                    "borderBottomRightRadius"      => 0,
                    "borderBottomRightRadiusHover" => 0,
                    "hasBorderRadiusAnimation"     => false,
                    "borderLeftWidth"              => 0,
                    "borderLeftWidthHover"         => 0,
                    "borderBottomLeftRadius"       => 0,
                    "borderBottomLeftRadiusHover"  => 0,
                    "borderColor"                  => "",
                    "borderColorHover"             => "",
                    "borderStyle"                  => 0,
                    "borderStyleHover"             => 0,
                    "hasBorderAnimation"           => false,
                    "width"                        => 0,
                ],
            ],
        ];
    }

    /**
     * Data provider for CRUD. Duplicate
     *
     * @return array
     */
    public function getDataProviderDuplicate()
    {
        $this->markTestSkipped();
        return [];
    }
}