ee_applications_template_emails_client_index:
    path:     /
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:index }

ee_applications_template_emails_client_select_template:
    path:     /{email}
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:selectTemplate }

ee_applications_template_emails_client_fill_placeholders:
    path:     /{email}/{id}/placeholders
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:fillPlaceholders }

ee_applications_template_emails_client_preview:
    path:     /{email}/{id}/preview
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:preview }

ee_applications_template_emails_client_preview_iframe:
    path:     /preview-iframe/{id}
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:previewIframe }

ee_applications_template_emails_client_send:
    path:     /{email}/{id}/send
    defaults: { _controller: EEApplicationsTemplateEmailsBundle:Client:send }