<?php
//
//namespace testS\tests\unit\models;
//
//use testS\models\DesignBlockModel;
//
///**
// * Tests for model DesignTextModel
// *
// * @package testS\tests\unit\models
// */
//class DesignBlockModelTest extends AbstractModelTest
//{
//
//    /**
//     * Model object
//     *
//     * @return DesignBlockModel
//     */
//    protected function getModel()
//    {
//        return new DesignBlockModel;
//    }
//
//    /**
//     * Data provider for CRUD test
//     *
//     * @return array
//     */
//    public function dataProviderForCRUD()
//    {
//        return [
//            $this->_dataProviderForCRUDNull(),
//            $this->_dataProviderForCRUDEmpty(),
//            $this->_dataProviderForCRUDCorrect(),
//            $this->_dataProviderForCRUDIncorrectType(),
//            $this->_dataProviderForCRUDIncorrectValue()
//        ];
//    }
//
//    /**
//     * Insert: null data.
//     * Update: null data
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDNull()
//    {
//        return [
//            [],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => false,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => false,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => false,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => false,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => false,
//                "width"                        => 0,
//            ],
//            [],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => false,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => false,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => false,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => false,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => false,
//                "width"                        => 0,
//            ],
//        ];
//    }
//
//    /**
//     * Insert: empty values.
//     * Update: empty values.
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDEmpty()
//    {
//        return [
//            [
//                "marginTop"                    => "",
//                "marginRight"                  => "",
//                "marginBottom"                 => "",
//                "marginLeft"                   => "",
//                "paddingTop"                   => "",
//                "paddingRight"                 => "",
//                "paddingBottom"                => "",
//                "paddingLeft"                  => "",
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => "",
//                "borderTopWidth"               => "",
//                "borderTopLeftRadius"          => "",
//                "borderRightWidth"             => "",
//                "borderTopRightRadius"         => "",
//                "borderBottomWidth"            => "",
//                "borderBottomRightRadius"      => "",
//                "borderLeftWidth"              => "",
//                "borderBottomLeftRadius"       => "",
//                "borderColor"                  => "",
//                "borderStyle"                  => "",
//                "marginTopHover"               => "",
//                "marginRightHover"             => "",
//                "marginBottomHover"            => "",
//                "marginLeftHover"              => "",
//                "paddingTopHover"              => "",
//                "paddingRightHover"            => "",
//                "paddingBottomHover"           => "",
//                "paddingLeftHover"             => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => "",
//                "borderTopWidthHover"          => "",
//                "borderTopLeftRadiusHover"     => "",
//                "borderRightWidthHover"        => "",
//                "borderTopRightRadiusHover"    => "",
//                "borderBottomWidthHover"       => "",
//                "borderBottomRightRadiusHover" => "",
//                "borderLeftWidthHover"         => "",
//                "borderBottomLeftRadiusHover"  => "",
//                "borderColorHover"             => "",
//                "borderStyleHover"             => "",
//                "hasMarginAnimation"           => "",
//                "hasPaddingAnimation"          => "",
//                "hasBackgroundAnimation"       => "",
//                "hasBorderRadiusAnimation"     => "",
//                "hasBorderAnimation"           => "",
//                "width"                        => "",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => false,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => false,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => false,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => false,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => false,
//                "width"                        => 0,
//            ],
//            [
//                "marginTop"                    => "",
//                "marginRight"                  => "",
//                "marginBottom"                 => "",
//                "marginLeft"                   => "",
//                "paddingTop"                   => "",
//                "paddingRight"                 => "",
//                "paddingBottom"                => "",
//                "paddingLeft"                  => "",
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => "",
//                "borderTopWidth"               => "",
//                "borderTopLeftRadius"          => "",
//                "borderRightWidth"             => "",
//                "borderTopRightRadius"         => "",
//                "borderBottomWidth"            => "",
//                "borderBottomRightRadius"      => "",
//                "borderLeftWidth"              => "",
//                "borderBottomLeftRadius"       => "",
//                "borderColor"                  => "",
//                "borderStyle"                  => "",
//                "marginTopHover"               => "",
//                "marginRightHover"             => "",
//                "marginBottomHover"            => "",
//                "marginLeftHover"              => "",
//                "paddingTopHover"              => "",
//                "paddingRightHover"            => "",
//                "paddingBottomHover"           => "",
//                "paddingLeftHover"             => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => "",
//                "borderTopWidthHover"          => "",
//                "borderTopLeftRadiusHover"     => "",
//                "borderRightWidthHover"        => "",
//                "borderTopRightRadiusHover"    => "",
//                "borderBottomWidthHover"       => "",
//                "borderBottomRightRadiusHover" => "",
//                "borderLeftWidthHover"         => "",
//                "borderBottomLeftRadiusHover"  => "",
//                "borderColorHover"             => "",
//                "borderStyleHover"             => "",
//                "hasMarginAnimation"           => "",
//                "hasPaddingAnimation"          => "",
//                "hasBackgroundAnimation"       => "",
//                "hasBorderRadiusAnimation"     => "",
//                "hasBorderAnimation"           => "",
//                "width"                        => "",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => false,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => false,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => false,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => false,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => false,
//                "width"                        => 0,
//            ],
//        ];
//    }
//
//    /**
//     * Insert: correct values.
//     * Update: correct values
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDCorrect()
//    {
//        return [
//            [
//                "marginTop"                    => 10,
//                "marginRight"                  => 20,
//                "marginBottom"                 => 30,
//                "marginLeft"                   => 40,
//                "paddingTop"                   => 15,
//                "paddingRight"                 => 25,
//                "paddingBottom"                => 35,
//                "paddingLeft"                  => 45,
//                "backgroundColorFrom"          => "rgba(255,255,255,0.5)",
//                "backgroundColorTo"            => "rgb(0,0,0)",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 1,
//                "borderTopLeftRadius"          => 5,
//                "borderRightWidth"             => 2,
//                "borderTopRightRadius"         => 10,
//                "borderBottomWidth"            => 3,
//                "borderBottomRightRadius"      => 15,
//                "borderLeftWidth"              => 4,
//                "borderBottomLeftRadius"       => 20,
//                "borderColor"                  => "rgba(0,255,255,0.5)",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_SOLID,
//                "marginTopHover"               => 10,
//                "marginRightHover"             => 20,
//                "marginBottomHover"            => 30,
//                "marginLeftHover"              => 40,
//                "paddingTopHover"              => 15,
//                "paddingRightHover"            => 25,
//                "paddingBottomHover"           => 35,
//                "paddingLeftHover"             => 45,
//                "backgroundColorFromHover"     => "rgba(255,255,255,0.5)",
//                "backgroundColorToHover"       => "rgb(0,0,0)",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 1,
//                "borderTopLeftRadiusHover"     => 5,
//                "borderRightWidthHover"        => 2,
//                "borderTopRightRadiusHover"    => 10,
//                "borderBottomWidthHover"       => 3,
//                "borderBottomRightRadiusHover" => 15,
//                "borderLeftWidthHover"         => 4,
//                "borderBottomLeftRadiusHover"  => 20,
//                "borderColorHover"             => "rgba(0,255,255,0.5)",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_SOLID,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 1024,
//            ],
//            [
//                "marginTop"                    => 10,
//                "marginRight"                  => 20,
//                "marginBottom"                 => 30,
//                "marginLeft"                   => 40,
//                "paddingTop"                   => 15,
//                "paddingRight"                 => 25,
//                "paddingBottom"                => 35,
//                "paddingLeft"                  => 45,
//                "backgroundColorFrom"          => "rgba(255,255,255,0.5)",
//                "backgroundColorTo"            => "rgb(0,0,0)",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 1,
//                "borderTopLeftRadius"          => 5,
//                "borderRightWidth"             => 2,
//                "borderTopRightRadius"         => 10,
//                "borderBottomWidth"            => 3,
//                "borderBottomRightRadius"      => 15,
//                "borderLeftWidth"              => 4,
//                "borderBottomLeftRadius"       => 20,
//                "borderColor"                  => "rgba(0,255,255,0.5)",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_SOLID,
//                "marginTopHover"               => 10,
//                "marginRightHover"             => 20,
//                "marginBottomHover"            => 30,
//                "marginLeftHover"              => 40,
//                "paddingTopHover"              => 15,
//                "paddingRightHover"            => 25,
//                "paddingBottomHover"           => 35,
//                "paddingLeftHover"             => 45,
//                "backgroundColorFromHover"     => "rgba(255,255,255,0.5)",
//                "backgroundColorToHover"       => "rgb(0,0,0)",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 1,
//                "borderTopLeftRadiusHover"     => 5,
//                "borderRightWidthHover"        => 2,
//                "borderTopRightRadiusHover"    => 10,
//                "borderBottomWidthHover"       => 3,
//                "borderBottomRightRadiusHover" => 15,
//                "borderLeftWidthHover"         => 4,
//                "borderBottomLeftRadiusHover"  => 20,
//                "borderColorHover"             => "rgba(0,255,255,0.5)",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_SOLID,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 1024,
//            ],
//            [
//                "marginTop"                    => "5",
//                "marginRight"                  => "6",
//                "marginBottom"                 => "7",
//                "marginLeft"                   => "8",
//                "paddingTop"                   => "9",
//                "paddingRight"                 => "10",
//                "paddingBottom"                => "11",
//                "paddingLeft"                  => "12",
//                "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
//                "backgroundColorTo"            => "rgba(255,255,0,0.5)",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
//                "borderTopWidth"               => "3",
//                "borderTopLeftRadius"          => "4",
//                "borderRightWidth"             => "5",
//                "borderTopRightRadius"         => "6",
//                "borderBottomWidth"            => "7",
//                "borderBottomRightRadius"      => "8",
//                "borderLeftWidth"              => "9",
//                "borderBottomLeftRadius"       => "10",
//                "borderColor"                  => "rgb(0,255,0)",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_DOTTED,
//                "marginTopHover"               => "5",
//                "marginRightHover"             => "6",
//                "marginBottomHover"            => "7",
//                "marginLeftHover"              => "8",
//                "paddingTopHover"              => "9",
//                "paddingRightHover"            => "10",
//                "paddingBottomHover"           => "11",
//                "paddingLeftHover"             => "12",
//                "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
//                "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
//                "borderTopWidthHover"          => "3",
//                "borderTopLeftRadiusHover"     => "4",
//                "borderRightWidthHover"        => "5",
//                "borderTopRightRadiusHover"    => "6",
//                "borderBottomWidthHover"       => "7",
//                "borderBottomRightRadiusHover" => "8",
//                "borderLeftWidthHover"         => "9",
//                "borderBottomLeftRadiusHover"  => "10",
//                "borderColorHover"             => "rgb(0,255,0)",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_DOTTED,
//                "hasMarginAnimation"           => false,
//                "hasPaddingAnimation"          => false,
//                "hasBackgroundAnimation"       => false,
//                "hasBorderRadiusAnimation"     => false,
//                "hasBorderAnimation"           => false,
//                "width"                        => 980,
//            ],
//            [
//                "marginTop"                    => 5,
//                "marginRight"                  => 6,
//                "marginBottom"                 => 7,
//                "marginLeft"                   => 8,
//                "paddingTop"                   => 9,
//                "paddingRight"                 => 10,
//                "paddingBottom"                => 11,
//                "paddingLeft"                  => 12,
//                "backgroundColorFrom"          => "rgba(255,0,255,0.5)",
//                "backgroundColorTo"            => "rgba(255,255,0,0.5)",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
//                "borderTopWidth"               => 3,
//                "borderTopLeftRadius"          => 4,
//                "borderRightWidth"             => 5,
//                "borderTopRightRadius"         => 6,
//                "borderBottomWidth"            => 7,
//                "borderBottomRightRadius"      => 8,
//                "borderLeftWidth"              => 9,
//                "borderBottomLeftRadius"       => 10,
//                "borderColor"                  => "rgb(0,255,0)",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_DOTTED,
//                "marginTopHover"               => "5",
//                "marginRightHover"             => "6",
//                "marginBottomHover"            => "7",
//                "marginLeftHover"              => "8",
//                "paddingTopHover"              => "9",
//                "paddingRightHover"            => "10",
//                "paddingBottomHover"           => "11",
//                "paddingLeftHover"             => "12",
//                "backgroundColorFromHover"     => "rgba(255,0,255,0.5)",
//                "backgroundColorToHover"       => "rgba(255,255,0,0.5)",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_VERTICAL,
//                "borderTopWidthHover"          => "3",
//                "borderTopLeftRadiusHover"     => "4",
//                "borderRightWidthHover"        => "5",
//                "borderTopRightRadiusHover"    => "6",
//                "borderBottomWidthHover"       => "7",
//                "borderBottomRightRadiusHover" => "8",
//                "borderLeftWidthHover"         => "9",
//                "borderBottomLeftRadiusHover"  => "10",
//                "borderColorHover"             => "rgb(0,255,0)",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_DOTTED,
//                "hasMarginAnimation"           => false,
//                "hasPaddingAnimation"          => false,
//                "hasBackgroundAnimation"       => false,
//                "hasBorderRadiusAnimation"     => false,
//                "hasBorderAnimation"           => false,
//                "width"                        => 980,
//            ]
//        ];
//    }
//
//    /**
//     * Insert: values with incorrect type
//     * Update: values with incorrect type
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDIncorrectType()
//    {
//        return [
//            [
//                "marginTop"                    => "incorrect type",
//                "marginRight"                  => "incorrect type",
//                "marginBottom"                 => "incorrect type",
//                "marginLeft"                   => "incorrect type",
//                "paddingTop"                   => "incorrect type",
//                "paddingRight"                 => "incorrect type",
//                "paddingBottom"                => "incorrect type",
//                "paddingLeft"                  => "incorrect type",
//                "backgroundColorFrom"          => "incorrect type",
//                "backgroundColorTo"            => "incorrect type",
//                "gradientDirection"            => "incorrect type",
//                "borderTopWidth"               => "incorrect type",
//                "borderTopLeftRadius"          => "incorrect type",
//                "borderRightWidth"             => "incorrect type",
//                "borderTopRightRadius"         => "incorrect type",
//                "borderBottomWidth"            => "incorrect type",
//                "borderBottomRightRadius"      => "incorrect type",
//                "borderLeftWidth"              => "incorrect type",
//                "borderBottomLeftRadius"       => "incorrect type",
//                "borderColor"                  => "0,255,255,0.5",
//                "borderStyle"                  => "incorrect type",
//                "marginTopHover"               => "incorrect type",
//                "marginRightHover"             => "incorrect type",
//                "marginBottomHover"            => "incorrect type",
//                "marginLeftHover"              => "incorrect type",
//                "paddingTopHover"              => "incorrect type",
//                "paddingRightHover"            => "incorrect type",
//                "paddingBottomHover"           => "incorrect type",
//                "paddingLeftHover"             => "incorrect type",
//                "backgroundColorFromHover"     => "incorrect type",
//                "backgroundColorToHover"       => "incorrect type",
//                "gradientDirectionHover"       => "incorrect type",
//                "borderTopWidthHover"          => "incorrect type",
//                "borderTopLeftRadiusHover"     => "incorrect type",
//                "borderRightWidthHover"        => "incorrect type",
//                "borderTopRightRadiusHover"    => "incorrect type",
//                "borderBottomWidthHover"       => "incorrect type",
//                "borderBottomRightRadiusHover" => "incorrect type",
//                "borderLeftWidthHover"         => "incorrect type",
//                "borderBottomLeftRadiusHover"  => "incorrect type",
//                "borderColorHover"             => "0,255,255,0.5",
//                "borderStyleHover"             => "incorrect type",
//                "hasMarginAnimation"           => "incorrect type",
//                "hasPaddingAnimation"          => "incorrect type",
//                "hasBackgroundAnimation"       => "incorrect type",
//                "hasBorderRadiusAnimation"     => "incorrect type",
//                "hasBorderAnimation"           => "incorrect type",
//                "width"                        => "incorrect type",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => true,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => true,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => true,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => true,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//            [
//                "marginTop"                    => "incorrect type",
//                "marginRight"                  => "incorrect type",
//                "marginBottom"                 => "incorrect type",
//                "marginLeft"                   => "incorrect type",
//                "paddingTop"                   => "incorrect type",
//                "paddingRight"                 => "incorrect type",
//                "paddingBottom"                => "incorrect type",
//                "paddingLeft"                  => "incorrect type",
//                "backgroundColorFrom"          => "incorrect type",
//                "backgroundColorTo"            => "incorrect type",
//                "gradientDirection"            => "incorrect type",
//                "borderTopWidth"               => "incorrect type",
//                "borderTopLeftRadius"          => "incorrect type",
//                "borderRightWidth"             => "incorrect type",
//                "borderTopRightRadius"         => "incorrect type",
//                "borderBottomWidth"            => "incorrect type",
//                "borderBottomRightRadius"      => "incorrect type",
//                "borderLeftWidth"              => "incorrect type",
//                "borderBottomLeftRadius"       => "incorrect type",
//                "borderColor"                  => "#cccccc",
//                "borderStyle"                  => "incorrect type",
//                "marginTopHover"               => "incorrect type",
//                "marginRightHover"             => "incorrect type",
//                "marginBottomHover"            => "incorrect type",
//                "marginLeftHover"              => "incorrect type",
//                "paddingTopHover"              => "incorrect type",
//                "paddingRightHover"            => "incorrect type",
//                "paddingBottomHover"           => "incorrect type",
//                "paddingLeftHover"             => "incorrect type",
//                "backgroundColorFromHover"     => "incorrect type",
//                "backgroundColorToHover"       => "incorrect type",
//                "gradientDirectionHover"       => "incorrect type",
//                "borderTopWidthHover"          => "incorrect type",
//                "borderTopLeftRadiusHover"     => "incorrect type",
//                "borderRightWidthHover"        => "incorrect type",
//                "borderTopRightRadiusHover"    => "incorrect type",
//                "borderBottomWidthHover"       => "incorrect type",
//                "borderBottomRightRadiusHover" => "incorrect type",
//                "borderLeftWidthHover"         => "incorrect type",
//                "borderBottomLeftRadiusHover"  => "incorrect type",
//                "borderColorHover"             => "0,255,255,0.5",
//                "borderStyleHover"             => "incorrect type",
//                "hasMarginAnimation"           => "incorrect type",
//                "hasPaddingAnimation"          => "incorrect type",
//                "hasBackgroundAnimation"       => "incorrect type",
//                "hasBorderRadiusAnimation"     => "incorrect type",
//                "hasBorderAnimation"           => "incorrect type",
//                "width"                        => "incorrect type",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => true,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => true,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => true,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => true,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//        ];
//    }
//
//    /**
//     * Insert: values with incorrect values
//     * Update: values with incorrect values
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDIncorrectValue()
//    {
//        return [
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTop"                   => -1,
//                "paddingRight"                 => -1,
//                "paddingBottom"                => -1,
//                "paddingLeft"                  => -1,
//                "backgroundColorFrom"          => "#ccc",
//                "backgroundColorTo"            => "#cccccc",
//                "gradientDirection"            => 99,
//                "borderTopWidth"               => -1,
//                "borderTopLeftRadius"          => -1,
//                "borderRightWidth"             => -1,
//                "borderTopRightRadius"         => -1,
//                "borderBottomWidth"            => -1,
//                "borderBottomRightRadius"      => -1,
//                "borderLeftWidth"              => -1,
//                "borderBottomLeftRadius"       => -1,
//                "borderColor"                  => "0,255,255",
//                "borderStyle"                  => 99,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTopHover"              => -1,
//                "paddingRightHover"            => -1,
//                "paddingBottomHover"           => -1,
//                "paddingLeftHover"             => -1,
//                "backgroundColorFromHover"     => "#ccc",
//                "backgroundColorToHover"       => "#cccccc",
//                "gradientDirectionHover"       => 99,
//                "borderTopWidthHover"          => -1,
//                "borderTopLeftRadiusHover"     => -1,
//                "borderRightWidthHover"        => -1,
//                "borderTopRightRadiusHover"    => -1,
//                "borderBottomWidthHover"       => -1,
//                "borderBottomRightRadiusHover" => -1,
//                "borderLeftWidthHover"         => -1,
//                "borderBottomLeftRadiusHover"  => -1,
//                "borderColorHover"             => "0,255,255",
//                "borderStyleHover"             => 99,
//                "hasMarginAnimation"           => 2,
//                "hasPaddingAnimation"          => 3,
//                "hasBackgroundAnimation"       => 4,
//                "hasBorderRadiusAnimation"     => 5,
//                "hasBorderAnimation"           => 6,
//                "width"                        => -10,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTop"                   => 0,
//                "paddingRight"                 => 0,
//                "paddingBottom"                => 0,
//                "paddingLeft"                  => 0,
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderRightWidth"             => 0,
//                "borderTopRightRadius"         => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderLeftWidth"              => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderColor"                  => "",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_NONE,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTopHover"              => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeftHover"             => 0,
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColorHover"             => "",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_NONE,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTop"                   => -1,
//                "paddingRight"                 => -1,
//                "paddingBottom"                => -1,
//                "paddingLeft"                  => -1,
//                "backgroundColorFrom"          => "0,255,255",
//                "backgroundColorTo"            => "0,0,255",
//                "gradientDirection"            => 111,
//                "borderTopWidth"               => -1,
//                "borderTopLeftRadius"          => -1,
//                "borderRightWidth"             => -1,
//                "borderTopRightRadius"         => -1,
//                "borderBottomWidth"            => -1,
//                "borderBottomRightRadius"      => -1,
//                "borderLeftWidth"              => -1,
//                "borderBottomLeftRadius"       => -1,
//                "borderColor"                  => "#cccccc",
//                "borderStyle"                  => 111,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTopHover"              => -1,
//                "paddingRightHover"            => -1,
//                "paddingBottomHover"           => -1,
//                "paddingLeftHover"             => -1,
//                "backgroundColorFromHover"     => "0,255,255",
//                "backgroundColorToHover"       => "0,0,255",
//                "gradientDirectionHover"       => 111,
//                "borderTopWidthHover"          => -1,
//                "borderTopLeftRadiusHover"     => -1,
//                "borderRightWidthHover"        => -1,
//                "borderTopRightRadiusHover"    => -1,
//                "borderBottomWidthHover"       => -1,
//                "borderBottomRightRadiusHover" => -1,
//                "borderLeftWidthHover"         => -1,
//                "borderBottomLeftRadiusHover"  => -1,
//                "borderColorHover"             => "#cccccc",
//                "borderStyleHover"             => 111,
//                "hasMarginAnimation"           => -1,
//                "hasPaddingAnimation"          => -2,
//                "hasBackgroundAnimation"       => -3,
//                "hasBorderRadiusAnimation"     => -4,
//                "hasBorderAnimation"           => -5,
//                "width"                        => -1,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTop"                   => 0,
//                "paddingRight"                 => 0,
//                "paddingBottom"                => 0,
//                "paddingLeft"                  => 0,
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderRightWidth"             => 0,
//                "borderTopRightRadius"         => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderLeftWidth"              => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderColor"                  => "",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_NONE,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTopHover"              => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeftHover"             => 0,
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColorHover"             => "",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_NONE,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ]
//        ];
//    }
//}