<?php

//    /**
//     * Insert: correct values.
//     * Update: correct values
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDCorrect()
//    {
//        return ;
//    }
//
//    /**
//     * Insert: values with incorrect type
//     * Update: values with incorrect type
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDIncorrectType()
//    {
//        return [
//            [
//                "marginTop"                    => "incorrect type",
//                "marginRight"                  => "incorrect type",
//                "marginBottom"                 => "incorrect type",
//                "marginLeft"                   => "incorrect type",
//                "paddingTop"                   => "incorrect type",
//                "paddingRight"                 => "incorrect type",
//                "paddingBottom"                => "incorrect type",
//                "paddingLeft"                  => "incorrect type",
//                "backgroundColorFrom"          => "incorrect type",
//                "backgroundColorTo"            => "incorrect type",
//                "gradientDirection"            => "incorrect type",
//                "borderTopWidth"               => "incorrect type",
//                "borderTopLeftRadius"          => "incorrect type",
//                "borderRightWidth"             => "incorrect type",
//                "borderTopRightRadius"         => "incorrect type",
//                "borderBottomWidth"            => "incorrect type",
//                "borderBottomRightRadius"      => "incorrect type",
//                "borderLeftWidth"              => "incorrect type",
//                "borderBottomLeftRadius"       => "incorrect type",
//                "borderColor"                  => "0,255,255,0.5",
//                "borderStyle"                  => "incorrect type",
//                "marginTopHover"               => "incorrect type",
//                "marginRightHover"             => "incorrect type",
//                "marginBottomHover"            => "incorrect type",
//                "marginLeftHover"              => "incorrect type",
//                "paddingTopHover"              => "incorrect type",
//                "paddingRightHover"            => "incorrect type",
//                "paddingBottomHover"           => "incorrect type",
//                "paddingLeftHover"             => "incorrect type",
//                "backgroundColorFromHover"     => "incorrect type",
//                "backgroundColorToHover"       => "incorrect type",
//                "gradientDirectionHover"       => "incorrect type",
//                "borderTopWidthHover"          => "incorrect type",
//                "borderTopLeftRadiusHover"     => "incorrect type",
//                "borderRightWidthHover"        => "incorrect type",
//                "borderTopRightRadiusHover"    => "incorrect type",
//                "borderBottomWidthHover"       => "incorrect type",
//                "borderBottomRightRadiusHover" => "incorrect type",
//                "borderLeftWidthHover"         => "incorrect type",
//                "borderBottomLeftRadiusHover"  => "incorrect type",
//                "borderColorHover"             => "0,255,255,0.5",
//                "borderStyleHover"             => "incorrect type",
//                "hasMarginAnimation"           => "incorrect type",
//                "hasPaddingAnimation"          => "incorrect type",
//                "hasBackgroundAnimation"       => "incorrect type",
//                "hasBorderRadiusAnimation"     => "incorrect type",
//                "hasBorderAnimation"           => "incorrect type",
//                "width"                        => "incorrect type",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => true,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => true,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => true,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => true,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//            [
//                "marginTop"                    => "incorrect type",
//                "marginRight"                  => "incorrect type",
//                "marginBottom"                 => "incorrect type",
//                "marginLeft"                   => "incorrect type",
//                "paddingTop"                   => "incorrect type",
//                "paddingRight"                 => "incorrect type",
//                "paddingBottom"                => "incorrect type",
//                "paddingLeft"                  => "incorrect type",
//                "backgroundColorFrom"          => "incorrect type",
//                "backgroundColorTo"            => "incorrect type",
//                "gradientDirection"            => "incorrect type",
//                "borderTopWidth"               => "incorrect type",
//                "borderTopLeftRadius"          => "incorrect type",
//                "borderRightWidth"             => "incorrect type",
//                "borderTopRightRadius"         => "incorrect type",
//                "borderBottomWidth"            => "incorrect type",
//                "borderBottomRightRadius"      => "incorrect type",
//                "borderLeftWidth"              => "incorrect type",
//                "borderBottomLeftRadius"       => "incorrect type",
//                "borderColor"                  => "#cccccc",
//                "borderStyle"                  => "incorrect type",
//                "marginTopHover"               => "incorrect type",
//                "marginRightHover"             => "incorrect type",
//                "marginBottomHover"            => "incorrect type",
//                "marginLeftHover"              => "incorrect type",
//                "paddingTopHover"              => "incorrect type",
//                "paddingRightHover"            => "incorrect type",
//                "paddingBottomHover"           => "incorrect type",
//                "paddingLeftHover"             => "incorrect type",
//                "backgroundColorFromHover"     => "incorrect type",
//                "backgroundColorToHover"       => "incorrect type",
//                "gradientDirectionHover"       => "incorrect type",
//                "borderTopWidthHover"          => "incorrect type",
//                "borderTopLeftRadiusHover"     => "incorrect type",
//                "borderRightWidthHover"        => "incorrect type",
//                "borderTopRightRadiusHover"    => "incorrect type",
//                "borderBottomWidthHover"       => "incorrect type",
//                "borderBottomRightRadiusHover" => "incorrect type",
//                "borderLeftWidthHover"         => "incorrect type",
//                "borderBottomLeftRadiusHover"  => "incorrect type",
//                "borderColorHover"             => "0,255,255,0.5",
//                "borderStyleHover"             => "incorrect type",
//                "hasMarginAnimation"           => "incorrect type",
//                "hasPaddingAnimation"          => "incorrect type",
//                "hasBackgroundAnimation"       => "incorrect type",
//                "hasBorderRadiusAnimation"     => "incorrect type",
//                "hasBorderAnimation"           => "incorrect type",
//                "width"                        => "incorrect type",
//            ],
//            [
//                "marginTop"                    => 0,
//                "marginTopHover"               => 0,
//                "marginRight"                  => 0,
//                "marginRightHover"             => 0,
//                "marginBottom"                 => 0,
//                "marginBottomHover"            => 0,
//                "marginLeft"                   => 0,
//                "marginLeftHover"              => 0,
//                "hasMarginAnimation"           => true,
//                "paddingTop"                   => 0,
//                "paddingTopHover"              => 0,
//                "paddingRight"                 => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottom"                => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeft"                  => 0,
//                "paddingLeftHover"             => 0,
//                "hasPaddingAnimation"          => true,
//                "backgroundColorFrom"          => "",
//                "backgroundColorFromHover"     => "",
//                "backgroundColorTo"            => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirection"            => 0,
//                "gradientDirectionHover"       => 0,
//                "hasBackgroundAnimation"       => true,
//                "borderTopWidth"               => 0,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidth"             => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadius"         => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "hasBorderRadiusAnimation"     => true,
//                "borderLeftWidth"              => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColor"                  => "",
//                "borderColorHover"             => "",
//                "borderStyle"                  => 0,
//                "borderStyleHover"             => 0,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//        ];
//    }
//
//    /**
//     * Insert: values with incorrect values
//     * Update: values with incorrect values
//     *
//     * @return array
//     */
//    private function _dataProviderForCRUDIncorrectValue()
//    {
//        return [
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTop"                   => -1,
//                "paddingRight"                 => -1,
//                "paddingBottom"                => -1,
//                "paddingLeft"                  => -1,
//                "backgroundColorFrom"          => "#ccc",
//                "backgroundColorTo"            => "#cccccc",
//                "gradientDirection"            => 99,
//                "borderTopWidth"               => -1,
//                "borderTopLeftRadius"          => -1,
//                "borderRightWidth"             => -1,
//                "borderTopRightRadius"         => -1,
//                "borderBottomWidth"            => -1,
//                "borderBottomRightRadius"      => -1,
//                "borderLeftWidth"              => -1,
//                "borderBottomLeftRadius"       => -1,
//                "borderColor"                  => "0,255,255",
//                "borderStyle"                  => 99,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTopHover"              => -1,
//                "paddingRightHover"            => -1,
//                "paddingBottomHover"           => -1,
//                "paddingLeftHover"             => -1,
//                "backgroundColorFromHover"     => "#ccc",
//                "backgroundColorToHover"       => "#cccccc",
//                "gradientDirectionHover"       => 99,
//                "borderTopWidthHover"          => -1,
//                "borderTopLeftRadiusHover"     => -1,
//                "borderRightWidthHover"        => -1,
//                "borderTopRightRadiusHover"    => -1,
//                "borderBottomWidthHover"       => -1,
//                "borderBottomRightRadiusHover" => -1,
//                "borderLeftWidthHover"         => -1,
//                "borderBottomLeftRadiusHover"  => -1,
//                "borderColorHover"             => "0,255,255",
//                "borderStyleHover"             => 99,
//                "hasMarginAnimation"           => 2,
//                "hasPaddingAnimation"          => 3,
//                "hasBackgroundAnimation"       => 4,
//                "hasBorderRadiusAnimation"     => 5,
//                "hasBorderAnimation"           => 6,
//                "width"                        => -10,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTop"                   => 0,
//                "paddingRight"                 => 0,
//                "paddingBottom"                => 0,
//                "paddingLeft"                  => 0,
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderRightWidth"             => 0,
//                "borderTopRightRadius"         => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderLeftWidth"              => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderColor"                  => "",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_NONE,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTopHover"              => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeftHover"             => 0,
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColorHover"             => "",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_NONE,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTop"                   => -1,
//                "paddingRight"                 => -1,
//                "paddingBottom"                => -1,
//                "paddingLeft"                  => -1,
//                "backgroundColorFrom"          => "0,255,255",
//                "backgroundColorTo"            => "0,0,255",
//                "gradientDirection"            => 111,
//                "borderTopWidth"               => -1,
//                "borderTopLeftRadius"          => -1,
//                "borderRightWidth"             => -1,
//                "borderTopRightRadius"         => -1,
//                "borderBottomWidth"            => -1,
//                "borderBottomRightRadius"      => -1,
//                "borderLeftWidth"              => -1,
//                "borderBottomLeftRadius"       => -1,
//                "borderColor"                  => "#cccccc",
//                "borderStyle"                  => 111,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE - 1,
//                "paddingTopHover"              => -1,
//                "paddingRightHover"            => -1,
//                "paddingBottomHover"           => -1,
//                "paddingLeftHover"             => -1,
//                "backgroundColorFromHover"     => "0,255,255",
//                "backgroundColorToHover"       => "0,0,255",
//                "gradientDirectionHover"       => 111,
//                "borderTopWidthHover"          => -1,
//                "borderTopLeftRadiusHover"     => -1,
//                "borderRightWidthHover"        => -1,
//                "borderTopRightRadiusHover"    => -1,
//                "borderBottomWidthHover"       => -1,
//                "borderBottomRightRadiusHover" => -1,
//                "borderLeftWidthHover"         => -1,
//                "borderBottomLeftRadiusHover"  => -1,
//                "borderColorHover"             => "#cccccc",
//                "borderStyleHover"             => 111,
//                "hasMarginAnimation"           => -1,
//                "hasPaddingAnimation"          => -2,
//                "hasBackgroundAnimation"       => -3,
//                "hasBorderRadiusAnimation"     => -4,
//                "hasBorderAnimation"           => -5,
//                "width"                        => -1,
//            ],
//            [
//                "marginTop"                    => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRight"                  => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottom"                 => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeft"                   => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTop"                   => 0,
//                "paddingRight"                 => 0,
//                "paddingBottom"                => 0,
//                "paddingLeft"                  => 0,
//                "backgroundColorFrom"          => "",
//                "backgroundColorTo"            => "",
//                "gradientDirection"            => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidth"               => 0,
//                "borderTopLeftRadius"          => 0,
//                "borderRightWidth"             => 0,
//                "borderTopRightRadius"         => 0,
//                "borderBottomWidth"            => 0,
//                "borderBottomRightRadius"      => 0,
//                "borderLeftWidth"              => 0,
//                "borderBottomLeftRadius"       => 0,
//                "borderColor"                  => "",
//                "borderStyle"                  => DesignBlockModel::BORDER_STYLE_NONE,
//                "marginTopHover"               => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginRightHover"             => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginBottomHover"            => DesignBlockModel::MIN_MARGIN_VALUE,
//                "marginLeftHover"              => DesignBlockModel::MIN_MARGIN_VALUE,
//                "paddingTopHover"              => 0,
//                "paddingRightHover"            => 0,
//                "paddingBottomHover"           => 0,
//                "paddingLeftHover"             => 0,
//                "backgroundColorFromHover"     => "",
//                "backgroundColorToHover"       => "",
//                "gradientDirectionHover"       => DesignBlockModel::GRADIENT_DIRECTION_HORIZONTAL,
//                "borderTopWidthHover"          => 0,
//                "borderTopLeftRadiusHover"     => 0,
//                "borderRightWidthHover"        => 0,
//                "borderTopRightRadiusHover"    => 0,
//                "borderBottomWidthHover"       => 0,
//                "borderBottomRightRadiusHover" => 0,
//                "borderLeftWidthHover"         => 0,
//                "borderBottomLeftRadiusHover"  => 0,
//                "borderColorHover"             => "",
//                "borderStyleHover"             => DesignBlockModel::BORDER_STYLE_NONE,
//                "hasMarginAnimation"           => true,
//                "hasPaddingAnimation"          => true,
//                "hasBackgroundAnimation"       => true,
//                "hasBorderRadiusAnimation"     => true,
//                "hasBorderAnimation"           => true,
//                "width"                        => 0,
//            ]
//        ];
//    }
//}