#!/usr/bin/env php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', 'On');

require(__DIR__ . "/../application/App.php");

use ss\application\App;

// Config file path
$config = require(__DIR__ . "/../config/common.php");

spl_autoload_register(['ss\application\App','autoload']);

// Runs a command
App::console($config)->run();
